services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    ports:
      - "9870:9870"  # HDFS Web UI
      - "50070:50070"  # Default Hadoop 2.x UI fallback
    environment:
      - CLUSTER_NAME=demo-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HDFS_SITE_dfs_namenode_http_address=0.0.0.0:9870
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks:
      - hadoopnet

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - CLUSTER_NAME=demo-cluster
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    networks:
      - hadoopnet

  pyspark:
    image: jupyter/pyspark-notebook:latest
    container_name: pyspark-jupyter
    ports:
      - "8888:8888"  # Jupyter UI
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./examples:/home/jovyan/examples  # Preloaded notebooks
    networks:
      - hadoopnet
    depends_on:
      - spark-master
    command: >
      start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
    ports:
      - "8080:8080"  # Spark Master UI
    networks:
      - hadoopnet

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    networks:
      - hadoopnet
    depends_on:
      - spark-master

volumes:
  hadoop_namenode:
  hadoop_datanode:

networks:
  hadoopnet:
    driver: bridge
